In [1]:
import pandas as pd
import numpy as np
import sklearn

In [2]:
df = pd.read_csv('medical_cost_prediction_dataset.csv')

In [3]:
df.head()

   age  gender   bmi smoker  ...  insurance_coverage_pct   city_type  previous_year_cost  annual_medical_cost
0   69    Male  29.4     No  ...                      80  Semi-Urban               10885              2645.50
1   32  Female  22.9     No  ...                      64  Semi-Urban               18722             10959.70
2   89    Male  25.7     No  ...                       0       Urban                4196              8409.80
3   78    Male  31.9    Yes  ...                      70       Urban               11128              7996.62
4   38    Male  27.7     No  ...                      77       Urban               15110              3202.52

[5 rows x 20 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   str
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   str
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   str
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           3952 non-null   str
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   str
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), str(5)
memory usage: 903.4 KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
smoker                        0
diabetes                      0
hypertension                  0
heart_disease                 0
asthma                        0
physical_activity_level       0
daily_steps                   0
sleep_hours                   0
stress_level                  0
doctor_visits_per_year        0
hospital_admissions           0
medication_count              0
insurance_type             1048
insurance_coverage_pct        0
city_type                     0
previous_year_cost            0
annual_medical_cost           0
dtype: int64

In [7]:
df['insurance_type'].fillna('unknown',inplace = True)

C:\Users\kavya\AppData\Local\Temp\ipykernel_32272\616663838.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['insurance_type'].fillna('unknown',inplace = True)

0          Private
1       Government
2          unknown
3       Government
4          Private
           ...
4995    Government
4996       unknown
4997       Private
4998       Private
4999    Government
Name: insurance_type, Length: 5000, dtype: str

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   str
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   str
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   str
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           3952 non-null   str
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   str
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), str(5)
memory usage: 903.4 KB

In [9]:
for i in df.columns:
    print('*'*20,i,'*'*20)
    print(df[i].unique())
    print()

******************** age ********************
[69 32 89 78 38 41 20 39 70 19 47 55 81 77 50 75 66 76 59 79 64 68 72 24
 56 35 21 31 26 88 61 25 52 53 67 23 71 80 51 65 57 43 58 46 62 82 18 28
 22 45 29 40 54 44 60 30 49 83 74 87 73 36 85 34 86 33 37 84 48 42 63 27]

******************** gender ********************
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

******************** bmi ********************
[29.4 22.9 25.7 31.9 27.7 23.  22.8 21.7 23.3 29.8 24.9 19.3 34.8 27.6
 19.  23.8 26.6 34.5 20.5 30.9 33.  24.6 20.8 25.  25.8 29.3 31.5 22.3
 16.2 25.9 27.5 27.2 24.4 33.6 27.9 24.1 23.5 25.2 34.2 25.1 23.6 35.8
 28.3 26.4 26.2 14.1 29.7 26.7 28.1 22.4 23.9 31.1 36.4 28.2 19.6 25.4
 22.7 15.  34.  29.5 28.7 26.8 19.1 30.2 20.7 13.3 25.3 29.6 29.2 27.3
 32.  18.4 28.5 29.1 19.8 18.5 31.6 26.1 32.5 32.6 27.1 38.5 24.2 30.8
 34.4 34.3 32.1 17.6 36.2 21.1 28.  18.7 31.2 29.9 31.4 27.4 21.  26.
 24.3 27.  35.5 31.8 12.3 33.7 23.2 24.7 22.2 17.3 25.5 30.5 26.5 23.4
 13.2 17.1 21.3 28.4 34.6 21.9 27.8 30.3 22.1 11.8 32.8 33.8 33.2 30.7
 21.6 22.  32.9 22.6 21.4 18.6 18.8 32.7 40.1 19.4 26.9 21.2 32.3 19.7
 26.3 28.6 24.  15.6 28.8 16.5 19.9 24.8 23.1 28.9 33.1 17.2 19.2 25.6
 17.9 35.4 21.8 19.5 36.5 29.  35.7 13.5 41.5 35.1 14.5 39.5 13.8 20.4
 30.1 20.  15.4 40.6 17.  14.9 24.5 32.2 22.5 32.4 14.  14.7 31.  18.1
 13.4 31.3 21.5 11.5 30.  16.6 14.4 37.2 18.3 17.7 36.3 15.2 34.1 36.
 20.1 31.7 36.9 17.8 18.9 17.5 37.  33.5 39.2 37.9 20.3 37.7 35.3 18.2
 30.4 33.9 17.4 20.6 12.4 37.5 20.2 13.6 30.6 33.3 16.3 37.6 39.9 36.7
 16.1 34.9 18.  33.4 23.7 12.9 16.9 15.9 20.9 12.5 12.6 16.8 34.7 37.8
 15.8 35.  40.7 14.2 15.5 35.2 38.2 38.6 43.6 38.8 39.3 35.6 14.6 39.6
  9.9 12.7 15.7 36.6 41.6 16.4 38.3 35.9 11.2 10.8 37.4 40.  14.8 12.1
 38.   7.6 15.3  8.  39.  11.7 40.3 38.1 36.8 10.3 37.3 41.   9.8  6.8
 42.9 11.3 37.1 38.9 41.8 16.  36.1 39.8 16.7 12.  38.7  6.4 14.3 13.7]

******************** smoker ********************
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

******************** diabetes ********************
[1 0]

******************** hypertension ********************
[0 1]

******************** heart_disease ********************
[0 1]

******************** asthma ********************
[0 1]

******************** physical_activity_level ********************
<ArrowStringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

******************** daily_steps ********************
[14825  3620 10578 ...  1517  8379  2000]

******************** sleep_hours ********************
[4.4 6.  4.5 8.6 5.7 7.7 4.6 7.4 8.2 5.  6.1 7.1 8.  6.7 8.4 8.3 6.9 9.
 6.4 7.9 4.7 8.9 5.8 5.1 5.4 4.3 6.5 5.9 5.5 6.8 6.3 5.2 7.8 8.8 6.2 7.
 4.1 7.6 8.7 7.2 8.1 8.5 7.5 4.  4.2 4.9 5.3 5.6 6.6 4.8 7.3]

******************** stress_level ********************
[ 8  7  9  3 10  6  4  1  5  2]

******************** doctor_visits_per_year ********************
[ 1  4  2  6  5  3  8  0  7 12  9 11 13 10 14]

******************** hospital_admissions ********************
[0 3 1 2 4 5 6]

******************** medication_count ********************
[4 0 3 7 6 2 1 5]

******************** insurance_type ********************
<ArrowStringArray>
['Private', 'Government', nan]
Length: 3, dtype: str

******************** insurance_coverage_pct ********************
[80 64  0 70 77 89 71 66 54 50 82 63 52 51 72 83 53 78 62 69 87 93 61 67
 73 79 68 59 88 56 90 65 55 58 57 76 92 81 74 75 84 94 60 85 91 86]

******************** city_type ********************
<ArrowStringArray>
['Semi-Urban', 'Urban', 'Rural']
Length: 3, dtype: str

******************** previous_year_cost ********************
[10885 18722  4196 ... 16543 11310 17078]

******************** annual_medical_cost ********************
[ 2645.5  10959.7   8409.8  ...  3354.62  1401.72  6548.04]

In [10]:
df.head()

   age  gender   bmi smoker  ...  insurance_coverage_pct   city_type  previous_year_cost  annual_medical_cost
0   69    Male  29.4     No  ...                      80  Semi-Urban               10885              2645.50
1   32  Female  22.9     No  ...                      64  Semi-Urban               18722             10959.70
2   89    Male  25.7     No  ...                       0       Urban                4196              8409.80
3   78    Male  31.9    Yes  ...                      70       Urban               11128              7996.62
4   38    Male  27.7     No  ...                      77       Urban               15110              3202.52

[5 rows x 20 columns]

In [11]:
X=df.drop('annual_medical_cost',axis=1)
y=df[['annual_medical_cost']]

In [12]:
X

      age  gender   bmi smoker  ...  insurance_type  insurance_coverage_pct   city_type  previous_year_cost
0      69    Male  29.4     No  ...         Private                      80  Semi-Urban               10885
1      32  Female  22.9     No  ...      Government                      64  Semi-Urban               18722
2      89    Male  25.7     No  ...             NaN                       0       Urban                4196
3      78    Male  31.9    Yes  ...      Government                      70       Urban               11128
4      38    Male  27.7     No  ...         Private                      77       Urban               15110
...   ...     ...   ...    ...  ...             ...                     ...         ...                 ...
4995   77  Female  19.7    Yes  ...      Government                      77  Semi-Urban               17154
4996   43  Female  23.9    Yes  ...             NaN                       0       Urban                4797
4997   58  Female  31.1     No  ...         Private                      81  Semi-Urban               16543
4998   53    Male  27.6     No  ...         Private                      88       Urban               11310
4999   40    Male  25.8     No  ...      Government                      63       Urban               17078

[5000 rows x 19 columns]

In [13]:
y

      annual_medical_cost
0                 2645.50
1                10959.70
2                 8409.80
3                 7996.62
4                 3202.52
...                   ...
4995              3513.76
4996              9816.10
4997              3354.62
4998              1401.72
4999              6548.04

[5000 rows x 1 columns]

## step 2 --> split the data into train and test data

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size =0.8,random_state=42)

In [15]:
X_train

      age  gender   bmi smoker  ...  insurance_type  insurance_coverage_pct   city_type  previous_year_cost
4227   73    Male  27.4     No  ...         Private                      79       Urban               11798
4676   53  Female  22.5     No  ...         Private                      78  Semi-Urban                5956
800    52  Female  24.9     No  ...         Private                      85  Semi-Urban               14943
3671   49    Male  24.3     No  ...      Government                      64  Semi-Urban                6355
4193   40    Male  38.0     No  ...         Private                      80       Urban               19822
...   ...     ...   ...    ...  ...             ...                     ...         ...                 ...
4426   60    Male  29.0     No  ...             NaN                       0  Semi-Urban                6929
466    33  Female  25.6     No  ...         Private                      85       Urban               19576
3092   64  Female  24.4    Yes  ...      Government                      76       Urban                9218
3772   21  Female  31.3     No  ...      Government                      62       Urban                 859
860    74    Male  20.0     No  ...             NaN                       0  Semi-Urban               19631

[4000 rows x 19 columns]

In [16]:
for i in [X_train,X_test,y_train,y_test]:
    i.reset_index(drop=True,inplace=True)

In [17]:
X_train

      age  gender   bmi smoker  ...  insurance_type  insurance_coverage_pct   city_type  previous_year_cost
0      73    Male  27.4     No  ...         Private                      79       Urban               11798
1      53  Female  22.5     No  ...         Private                      78  Semi-Urban                5956
2      52  Female  24.9     No  ...         Private                      85  Semi-Urban               14943
3      49    Male  24.3     No  ...      Government                      64  Semi-Urban                6355
4      40    Male  38.0     No  ...         Private                      80       Urban               19822
...   ...     ...   ...    ...  ...             ...                     ...         ...                 ...
3995   60    Male  29.0     No  ...             NaN                       0  Semi-Urban                6929
3996   33  Female  25.6     No  ...         Private                      85       Urban               19576
3997   64  Female  24.4    Yes  ...      Government                      76       Urban                9218
3998   21  Female  31.3     No  ...      Government                      62       Urban                 859
3999   74    Male  20.0     No  ...             NaN                       0  Semi-Urban               19631

[4000 rows x 19 columns]

In [18]:
X_test

     age  gender   bmi smoker  ...  insurance_type  insurance_coverage_pct   city_type  previous_year_cost
0     36    Male  28.4     No  ...      Government                      65       Urban                7029
1     39    Male  14.1     No  ...             NaN                       0  Semi-Urban                7744
2     86  Female  24.7     No  ...         Private                      72       Rural                7592
3     39  Female  32.6     No  ...         Private                      93  Semi-Urban                7020
4     40  Female  30.8    Yes  ...      Government                      51       Urban               17125
..   ...     ...   ...    ...  ...             ...                     ...         ...                 ...
995   60    Male  31.6    Yes  ...      Government                      56       Urban               13923
996   78    Male  27.5     No  ...         Private                      92       Urban               19366
997   26    Male  27.2     No  ...      Government                      62       Urban                1428
998   54    Male  34.7    Yes  ...      Government                      79       Urban               16310
999   31    Male  22.2     No  ...         Private                      74  Semi-Urban               12739

[1000 rows x 19 columns]

In [19]:
y_train

      annual_medical_cost
0                 3952.49
1                 3590.80
2                 4330.49
3                 6377.58
4                 3617.32
...                   ...
3995             13948.70
3996              3165.12
3997              5802.58
3998              4718.35
3999             22569.30

[4000 rows x 1 columns]

## step 3 --> Feature Engineering

In [20]:
cat_train=X_train.select_dtypes(include='object')

C:\Users\kavya\AppData\Local\Temp\ipykernel_32272\1951577003.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_train=X_train.select_dtypes(include='object')

In [21]:
cat_train

      gender smoker physical_activity_level insurance_type   city_type
0       Male     No                    High        Private       Urban
1     Female     No                     Low        Private  Semi-Urban
2     Female     No                    High        Private  Semi-Urban
3       Male     No                  Medium     Government  Semi-Urban
4       Male     No                  Medium        Private       Urban
...      ...    ...                     ...            ...         ...
3995    Male     No                  Medium            NaN  Semi-Urban
3996  Female     No                    High        Private       Urban
3997  Female    Yes                  Medium     Government       Urban
3998  Female     No                     Low     Government       Urban
3999    Male     No                     Low            NaN  Semi-Urban

[4000 rows x 5 columns]

In [22]:
num_train = X_train[['age','bmi','daily_steps','sleep_hours','stress_level','doctor_visits_per_year','insurance_coverage_pct','previous_year_cost']]

In [23]:
num_train

      age   bmi  daily_steps  ...  doctor_visits_per_year  insurance_coverage_pct  previous_year_cost
0      73  27.4         2806  ...                       1                      79               11798
1      53  22.5         6800  ...                       7                      78                5956
2      52  24.9         7567  ...                       7                      85               14943
3      49  24.3        11050  ...                       4                      64                6355
4      40  38.0         3463  ...                       3                      80               19822
...   ...   ...          ...  ...                     ...                     ...                 ...
3995   60  29.0         1898  ...                       3                       0                6929
3996   33  25.6        12035  ...                       3                      85               19576
3997   64  24.4        10186  ...                       7                      76                9218
3998   21  31.3         2878  ...                       7                      62                 859
3999   74  20.0         2959  ...                       6                       0               19631

[4000 rows x 8 columns]

In [24]:
no_train = X_train[['diabetes','hypertension','heart_disease','asthma','hospital_admissions','medication_count']]

In [25]:
no_train

      diabetes  hypertension  heart_disease  asthma  hospital_admissions  medication_count
0            0             0              0       0                    1                 6
1            0             0              1       0                    0                 4
2            0             1              0       0                    2                 6
3            1             0              1       0                    0                 5
4            0             0              0       0                    1                 2
...        ...           ...            ...     ...                  ...               ...
3995         0             0              0       0                    1                 2
3996         0             0              0       0                    1                 7
3997         0             1              1       0                    1                 0
3998         0             0              0       0                    1                 2
3999         0             0              1       0                    1                 1

[4000 rows x 6 columns]

In [26]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse_output = False).set_output(transform ='pandas')
cat_train_trans = OHE.fit_transform(cat_train)

In [27]:
cat_train_trans

      gender_Female  gender_Male  smoker_No  ...  city_type_Rural  city_type_Semi-Urban  city_type_Urban
0               0.0          1.0        1.0  ...              0.0                   0.0              1.0
1               1.0          0.0        1.0  ...              0.0                   1.0              0.0
2               1.0          0.0        1.0  ...              0.0                   1.0              0.0
3               0.0          1.0        1.0  ...              0.0                   1.0              0.0
4               0.0          1.0        1.0  ...              0.0                   0.0              1.0
...             ...          ...        ...  ...              ...                   ...              ...
3995            0.0          1.0        1.0  ...              0.0                   1.0              0.0
3996            1.0          0.0        1.0  ...              0.0                   0.0              1.0
3997            1.0          0.0        0.0  ...              0.0                   0.0              1.0
3998            1.0          0.0        1.0  ...              0.0                   0.0              1.0
3999            0.0          1.0        1.0  ...              0.0                   1.0              0.0

[4000 rows x 13 columns]

In [28]:
num_train

      age   bmi  daily_steps  ...  doctor_visits_per_year  insurance_coverage_pct  previous_year_cost
0      73  27.4         2806  ...                       1                      79               11798
1      53  22.5         6800  ...                       7                      78                5956
2      52  24.9         7567  ...                       7                      85               14943
3      49  24.3        11050  ...                       4                      64                6355
4      40  38.0         3463  ...                       3                      80               19822
...   ...   ...          ...  ...                     ...                     ...                 ...
3995   60  29.0         1898  ...                       3                       0                6929
3996   33  25.6        12035  ...                       3                      85               19576
3997   64  24.4        10186  ...                       7                      76                9218
3998   21  31.3         2878  ...                       7                      62                 859
3999   74  20.0         2959  ...                       6                       0               19631

[4000 rows x 8 columns]

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().set_output(transform ='pandas')

num_train_trans = scaler.fit_transform(num_train)

In [30]:
num_train_trans

           age       bmi  daily_steps  ...  doctor_visits_per_year  insurance_coverage_pct  previous_year_cost
0     0.774648  0.564516     0.128760  ...                0.071429                0.840426            0.579503
1     0.492958  0.432796     0.414148  ...                0.500000                0.829787            0.279852
2     0.478873  0.497312     0.468953  ...                0.500000                0.904255            0.740819
3     0.436620  0.481183     0.717828  ...                0.285714                0.680851            0.300318
4     0.309859  0.849462     0.175706  ...                0.214286                0.851064            0.991075
...        ...       ...          ...  ...                     ...                     ...                 ...
3995  0.591549  0.607527     0.063880  ...                0.214286                0.000000            0.329760
3996  0.211268  0.516129     0.788210  ...                0.214286                0.904255            0.978457
3997  0.647887  0.483871     0.656091  ...                0.500000                0.808511            0.447169
3998  0.042254  0.669355     0.133905  ...                0.500000                0.659574            0.018414
3999  0.788732  0.365591     0.139693  ...                0.428571                0.000000            0.981278

[4000 rows x 8 columns]

In [31]:
no_train

      diabetes  hypertension  heart_disease  asthma  hospital_admissions  medication_count
0            0             0              0       0                    1                 6
1            0             0              1       0                    0                 4
2            0             1              0       0                    2                 6
3            1             0              1       0                    0                 5
4            0             0              0       0                    1                 2
...        ...           ...            ...     ...                  ...               ...
3995         0             0              0       0                    1                 2
3996         0             0              0       0                    1                 7
3997         0             1              1       0                    1                 0
3998         0             0              0       0                    1                 2
3999         0             0              1       0                    1                 1

[4000 rows x 6 columns]

In [32]:
X_train_trans = pd.concat([cat_train_trans,num_train_trans,no_train],axis = 1)

In [33]:
X_train_trans

      gender_Female  gender_Male  smoker_No  smoker_Yes  ...  heart_disease  asthma  hospital_admissions  medication_count
0               0.0          1.0        1.0         0.0  ...              0       0                    1                 6
1               1.0          0.0        1.0         0.0  ...              1       0                    0                 4
2               1.0          0.0        1.0         0.0  ...              0       0                    2                 6
3               0.0          1.0        1.0         0.0  ...              1       0                    0                 5
4               0.0          1.0        1.0         0.0  ...              0       0                    1                 2
...             ...          ...        ...         ...  ...            ...     ...                  ...               ...
3995            0.0          1.0        1.0         0.0  ...              0       0                    1                 2
3996            1.0          0.0        1.0         0.0  ...              0       0                    1                 7
3997            1.0          0.0        0.0         1.0  ...              1       0                    1                 0
3998            1.0          0.0        1.0         0.0  ...              0       0                    1                 2
3999            0.0          1.0        1.0         0.0  ...              1       0                    1                 1

[4000 rows x 27 columns]

## step 4 --> Training model using algorithm

In [34]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor()

model.fit(X_train_trans,y_train)

KNeighborsRegressor()

## step 5 --> feature engineering on X_test

In [35]:
cat_test = X_test.select_dtypes(include='object')

C:\Users\kavya\AppData\Local\Temp\ipykernel_32272\98124595.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_test = X_test.select_dtypes(include='object')

In [36]:
cat_test

     gender smoker physical_activity_level insurance_type   city_type
0      Male     No                     Low     Government       Urban
1      Male     No                    High            NaN  Semi-Urban
2    Female     No                  Medium        Private       Rural
3    Female     No                     Low        Private  Semi-Urban
4    Female    Yes                     Low     Government       Urban
..      ...    ...                     ...            ...         ...
995    Male    Yes                     Low     Government       Urban
996    Male     No                     Low        Private       Urban
997    Male     No                     Low     Government       Urban
998    Male    Yes                    High     Government       Urban
999    Male     No                    High        Private  Semi-Urban

[1000 rows x 5 columns]

In [37]:
cat_test_trans = OHE.transform(cat_test)

In [38]:
cat_test_trans

     gender_Female  gender_Male  smoker_No  ...  city_type_Rural  city_type_Semi-Urban  city_type_Urban
0              0.0          1.0        1.0  ...              0.0                   0.0              1.0
1              0.0          1.0        1.0  ...              0.0                   1.0              0.0
2              1.0          0.0        1.0  ...              1.0                   0.0              0.0
3              1.0          0.0        1.0  ...              0.0                   1.0              0.0
4              1.0          0.0        0.0  ...              0.0                   0.0              1.0
..             ...          ...        ...  ...              ...                   ...              ...
995            0.0          1.0        0.0  ...              0.0                   0.0              1.0
996            0.0          1.0        1.0  ...              0.0                   0.0              1.0
997            0.0          1.0        1.0  ...              0.0                   0.0              1.0
998            0.0          1.0        0.0  ...              0.0                   0.0              1.0
999            0.0          1.0        1.0  ...              0.0                   1.0              0.0

[1000 rows x 13 columns]

In [39]:
num_test = X_test[['age','bmi','daily_steps','sleep_hours','stress_level','doctor_visits_per_year','insurance_coverage_pct','previous_year_cost']]

In [40]:
num_test_trans = scaler.transform(num_test)

In [41]:
num_test_trans

          age       bmi  daily_steps  ...  doctor_visits_per_year  insurance_coverage_pct  previous_year_cost
0    0.253521  0.591398     0.192712  ...                0.357143                0.691489            0.334889
1    0.295775  0.206989     0.146267  ...                0.285714                0.000000            0.371563
2    0.957746  0.491935     0.075384  ...                0.142857                0.765957            0.363767
3    0.295775  0.704301     0.552554  ...                0.357143                0.989362            0.334428
4    0.309859  0.655914     0.662165  ...                0.285714                0.542553            0.852739
..        ...       ...          ...  ...                     ...                     ...                 ...
995  0.591549  0.677419     0.168917  ...                0.285714                0.595745            0.688500
996  0.845070  0.567204     0.295034  ...                0.142857                0.978723            0.967686
997  0.112676  0.559140     0.111111  ...                0.357143                0.659574            0.047600
998  0.507042  0.760753     0.287746  ...                0.214286                0.840426            0.810936
999  0.183099  0.424731     0.230797  ...                0.071429                0.787234            0.627770

[1000 rows x 8 columns]

In [42]:
no_trans_test = X_test[['diabetes','hypertension','heart_disease','asthma','hospital_admissions','medication_count']]

In [43]:
X_test_trans = pd.concat([cat_test_trans,num_test_trans,no_trans_test],axis=1)

In [44]:
X_test_trans

     gender_Female  gender_Male  smoker_No  smoker_Yes  ...  heart_disease  asthma  hospital_admissions  medication_count
0              0.0          1.0        1.0         0.0  ...              0       0                    0                 0
1              0.0          1.0        1.0         0.0  ...              0       0                    3                 1
2              1.0          0.0        1.0         0.0  ...              0       0                    1                 3
3              1.0          0.0        1.0         0.0  ...              0       0                    2                 0
4              1.0          0.0        0.0         1.0  ...              0       0                    2                 1
..             ...          ...        ...         ...  ...            ...     ...                  ...               ...
995            0.0          1.0        0.0         1.0  ...              0       0                    3                 0
996            0.0          1.0        1.0         0.0  ...              0       0                    0                 2
997            0.0          1.0        1.0         0.0  ...              0       0                    0                 6
998            0.0          1.0        0.0         1.0  ...              0       0                    3                 1
999            0.0          1.0        1.0         0.0  ...              0       0                    3                 5

[1000 rows x 27 columns]

## step 6 prediction on X_test

In [45]:
y_pred = model.predict(X_test_trans)

In [46]:
y_pred

array([[ 3830.448],
       [23150.78 ],
       [ 3914.416],
       [ 3847.728],
       [ 6528.596],
       [ 2467.414],
       [ 5995.358],
       [ 3242.76 ],
       [ 3260.674],
       [18969.28 ],
       [17589.38 ],
       [ 3089.436],
       [ 3806.386],
       [ 3222.256],
       [ 8319.294],
       [ 7886.172],
       [ 7151.242],
       [ 6905.262],
       [ 5899.668],
       [ 4669.06 ],
       [ 4248.43 ],
       [ 6749.148],
       [11911.78 ],
       [ 7597.678],
       [13812.934],
       [10112.64 ],
       [ 2911.246],
       [ 4006.538],
       [ 4524.342],
       [ 7252.754],
       [18105.116],
       [ 7576.222],
       [ 5307.062],
       [ 2624.398],
       [ 3217.478],
       [13160.94 ],
       [ 2808.098],
       [ 2217.562],
       [ 7081.418],
       [14672.26 ],
       [ 2464.448],
       [11903.26 ],
       [13008.112],
       [ 5364.522],
       [ 4271.23 ],
       [ 6709.7  ],
       [ 3110.73 ],
       [ 2746.082],
       [17439.46 ],
       [ 3566.34 ],
       [ 8053.722],
       [ 7629.096],
       [ 5191.918],
       [18790.68 ],
       [ 3093.678],
       [ 5080.262],
       [15009.36 ],
       [21978.48 ],
       [ 4409.892],
       [ 8750.61 ],
       [11310.73 ],
       [ 5030.46 ],
       [ 7398.696],
       [13680.58 ],
       [ 4775.03 ],
       [ 5683.338],
       [20588.24 ],
       [ 4810.322],
       [ 6723.83 ],
       [17969.9  ],
       [16368.8  ],
       [10924.32 ],
       [ 8874.874],
       [16217.28 ],
       [ 4144.858],
       [ 2406.62 ],
       [ 3437.176],
       [ 3474.286],
       [18471.5  ],
       [ 4581.38 ],
       [ 8776.724],
       [23065.02 ],
       [ 6723.39 ],
       [ 4925.434],
       [ 7970.498],
       [19661.88 ],
       [11257.62 ],
       [ 2103.492],
       [22286.3  ],
       [ 4354.748],
       [ 4055.378],
       [ 4899.142],
       [ 2752.998],
       [13775.68 ],
       [ 4110.084],
       [18843.62 ],
       [16732.   ],
       [ 3937.214],
       [12602.82 ],
       [20109.58 ],
       [ 5268.79 ],
       [ 4330.41 ],
       [ 2223.662],
       [ 4546.386],
       [ 5870.698],
       [ 4451.874],
       [ 4801.634],
       [ 5070.042],
       [20068.64 ],
       [ 5140.366],
       [ 4085.374],
       [16925.24 ],
       [11921.1  ],
       [30077.17 ],
       [ 3992.396],
       [ 3979.448],
       [23194.04 ],
       [ 7172.718],
       [ 3447.862],
       [ 3915.274],
       [ 5892.152],
       [11026.658],
       [ 3573.646],
       [ 5345.096],
       [ 6978.778],
       [ 4186.414],
       [ 2699.246],
       [ 2406.494],
       [ 5200.548],
       [16832.1  ],
       [ 5112.1  ],
       [ 8794.894],
       [ 5070.694],
       [11079.62 ],
       [ 3540.534],
       [ 4791.542],
       [ 2094.016],
       [ 6582.53 ],
       [ 8403.346],
       [ 2284.908],
       [ 4043.634],
       [16080.28 ],
       [16053.6  ],
       [ 4073.964],
       [ 3356.98 ],
       [ 5827.084],
       [ 3116.114],
       [ 3512.738],
       [ 3297.532],
       [ 1639.154],
       [ 3395.686],
       [ 4864.596],
       [ 3194.492],
       [ 4690.546],
       [ 5356.816],
       [ 5072.956],
       [13369.86 ],
       [ 7105.894],
       [ 2475.444],
       [ 2447.192],
       [ 2214.548],
       [ 5955.068],
       [ 2985.442],
       [ 4192.334],
       [ 9356.782],
       [ 5681.646],
       [ 3485.866],
       [ 2971.164],
       [ 9659.502],
       [12032.6  ],
       [20466.26 ],
       [ 8574.302],
       [ 1896.658],
       [ 8290.274],
       [ 4882.48 ],
       [ 4604.04 ],
       [ 4365.642],
       [ 4832.592],
       [ 3504.998],
       [ 5856.31 ],
       [ 3761.322],
       [ 2065.454],
       [ 4073.996],
       [ 7131.426],
       [18888.18 ],
       [ 1951.2  ],
       [ 3896.562],
       [ 4044.736],
       [ 4978.378],
       [ 6464.326],
       [ 4399.478],
       [ 4767.096],
       [ 5117.254],
       [14942.04 ],
       [ 2885.638],
       [ 5039.654],
       [ 4534.296],
       [ 1500.078],
       [ 2048.724],
       [ 2905.608],
       [ 3047.412],
       [21805.52 ],
       [ 3870.564],
       [ 4064.552],
       [ 3459.918],
       [12414.24 ],
       [ 1689.278],
       [17711.56 ],
       [ 2141.864],
       [ 2182.282],
       [ 5235.254],
       [ 9676.426],
       [ 5848.776],
       [ 4559.79 ],
       [ 6111.914],
       [ 2503.934],
       [ 6368.634],
       [ 2636.27 ],
       [ 1733.544],
       [18156.9  ],
       [ 2996.082],
       [ 2976.488],
       [ 3528.638],
       [ 9511.28 ],
       [ 2926.92 ],
       [12812.666],
       [ 2563.832],
       [ 4483.82 ],
       [ 6418.82 ],
       [ 4949.702],
       [27366.24 ],
       [ 4499.99 ],
       [ 2505.818],
       [ 3283.778],
       [ 2215.442],
       [ 1636.588],
       [ 6552.814],
       [ 3083.564],
       [15848.76 ],
       [ 4658.232],
       [ 7046.826],
       [ 6541.28 ],
       [ 2186.596],
       [ 3185.53 ],
       [ 4776.656],
       [ 2403.866],
       [ 1575.418],
       [ 5507.91 ],
       [ 2477.158],
       [ 3126.086],
       [ 1376.802],
       [ 5833.448],
       [ 3118.252],
       [15626.46 ],
       [ 2206.462],
       [14183.51 ],
       [ 2742.124],
       [23662.94 ],
       [ 1096.342],
       [ 8241.224],
       [ 2605.404],
       [ 3024.102],
       [ 9217.826],
       [ 1542.83 ],
       [12831.148],
       [ 5957.566],
       [ 2123.798],
       [ 7614.016],
       [ 3311.32 ],
       [ 6429.86 ],
       [15129.32 ],
       [ 3844.25 ],
       [ 4966.588],
       [24571.94 ],
       [ 3239.608],
       [18045.32 ],
       [ 5348.016],
       [ 6400.44 ],
       [ 3157.644],
       [ 7129.822],
       [ 4353.82 ],
       [10812.82 ],
       [ 4234.638],
       [18467.748],
       [ 3280.372],
       [ 5737.668],
       [ 3452.654],
       [16668.86 ],
       [ 6101.118],
       [10293.202],
       [ 9025.006],
       [ 2630.154],
       [ 7515.968],
       [21550.76 ],
       [ 1403.096],
       [ 2913.738],
       [ 5054.394],
       [13879.8  ],
       [ 3506.962],
       [18867.36 ],
       [ 5738.874],
       [ 2915.77 ],
       [17018.2  ],
       [23536.06 ],
       [ 5437.772],
       [ 4673.436],
       [ 5894.162],
       [ 3344.522],
       [ 9959.94 ],
       [ 9097.322],
       [ 6511.064],
       [ 2735.348],
       [ 5407.77 ],
       [ 5165.878],
       [ 8906.228],
       [ 4764.442],
       [ 2335.752],
       [17035.9  ],
       [12930.   ],
       [ 2152.412],
       [16553.42 ],
       [ 5674.65 ],
       [19102.64 ],
       [ 4572.988],
       [ 5862.218],
       [ 5769.476],
       [11436.52 ],
       [ 3017.61 ],
       [ 2714.224],
       [ 2159.366],
       [ 2236.052],
       [ 4605.756],
       [ 6501.02 ],
       [ 4273.99 ],
       [ 4057.834],
       [21857.66 ],
       [ 2995.966],
       [ 5870.698],
       [ 2976.24 ],
       [ 7337.858],
       [ 5269.718],
       [15715.02 ],
       [ 7851.804],
       [13176.938],
       [ 2406.964],
       [ 4503.132],
       [ 5850.18 ],
       [ 4639.264],
       [ 2417.608],
       [ 3057.268],
       [ 4855.448],
       [ 9432.352],
       [ 3482.086],
       [ 2213.63 ],
       [ 9458.482],
       [ 8480.766],
       [ 3970.416],
       [ 1921.636],
       [ 6589.57 ],
       [ 3812.526],
       [22969.4  ],
       [ 3874.982],
       [ 5003.258],
       [ 7595.792],
       [21433.74 ],
       [ 3892.77 ],
       [ 6725.77 ],
       [ 2351.808],
       [ 7266.974],
       [17248.962],
       [15368.31 ],
       [ 8393.476],
       [15518.94 ],
       [13950.02 ],
       [ 4005.22 ],
       [18278.7  ],
       [12658.52 ],
       [ 6771.368],
       [ 4461.414],
       [ 2616.858],
       [ 8434.632],
       [ 9120.176],
       [ 1506.998],
       [ 4548.848],
       [ 5724.528],
       [ 5669.216],
       [ 4663.218],
       [ 3470.004],
       [ 3587.26 ],
       [ 1947.614],
       [10152.758],
       [ 3604.992],
       [ 6016.248],
       [ 7356.556],
       [ 2695.582],
       [ 3500.96 ],
       [ 2883.618],
       [ 4492.712],
       [ 3208.142],
       [ 5610.812],
       [ 1738.454],
       [ 4386.016],
       [ 4549.67 ],
       [32841.34 ],
       [ 1999.13 ],
       [13104.06 ],
       [16173.48 ],
       [ 4268.972],
       [ 5778.67 ],
       [ 5674.358],
       [10744.364],
       [17812.38 ],
       [ 7833.93 ],
       [ 7456.064],
       [14345.136],
       [ 4715.312],
       [10100.484],
       [ 5289.468],
       [ 6576.25 ],
       [ 5628.414],
       [ 3268.734],
       [ 3126.096],
       [10724.582],
       [ 6070.85 ],
       [ 2437.378],
       [ 2322.936],
       [27621.1  ],
       [ 9331.076],
       [13409.6  ],
       [ 7968.244],
       [ 8706.616],
       [ 2424.252],
       [22026.18 ],
       [ 7606.602],
       [17996.86 ],
       [ 3920.902],
       [ 8625.818],
       [ 3009.476],
       [10955.892],
       [ 4591.278],
       [ 2515.912],
       [19893.32 ],
       [ 2731.804],
       [ 4809.288],
       [ 5334.642],
       [ 5616.112],
       [ 5569.322],
       [ 2320.844],
       [25390.22 ],
       [ 3761.592],
       [11938.78 ],
       [19546.728],
       [ 7055.608],
       [ 4190.32 ],
       [ 3402.258],
       [ 6003.728],
       [ 8895.268],
       [ 2197.08 ],
       [ 6576.438],
       [ 2118.65 ],
       [ 4456.002],
       [20842.04 ],
       [ 5513.884],
       [ 3867.01 ],
       [10289.42 ],
       [35220.94 ],
       [ 5790.578],
       [ 6711.466],
       [ 9785.452],
       [ 1764.146],
       [26111.2  ],
       [16123.96 ],
       [10741.64 ],
       [ 3137.44 ],
       [ 4282.564],
       [20701.84 ],
       [ 3382.746],
       [ 4407.884],
       [ 5212.106],
       [ 2985.234],
       [19807.48 ],
       [16004.34 ],
       [ 5326.042],
       [ 6277.614],
       [ 3139.022],
       [ 4166.884],
       [ 2227.586],
       [ 5064.73 ],
       [17914.46 ],
       [ 3757.574],
       [13824.88 ],
       [ 2643.24 ],
       [ 6425.82 ],
       [10043.986],
       [ 4331.226],
       [ 2733.712],
       [ 2811.336],
       [ 3322.244],
       [ 3289.606],
       [ 8585.842],
       [ 3540.636],
       [ 8784.204],
       [15286.22 ],
       [ 5622.784],
       [ 2118.648],
       [ 2033.95 ],
       [ 3051.128],
       [22189.48 ],
       [ 5704.98 ],
       [ 3080.746],
       [ 2086.616],
       [ 4556.65 ],
       [ 9403.254],
       [ 5354.974],
       [ 2378.664],
       [ 3863.14 ],
       [ 1873.834],
       [ 5299.492],
       [ 5724.066],
       [ 9145.056],
       [ 3432.446],
       [ 2032.8  ],
       [ 7646.764],
       [ 1947.572],
       [ 8133.866],
       [ 4411.564],
       [ 5025.282],
       [13748.86 ],
       [10677.52 ],
       [16534.94 ],
       [ 3993.106],
       [ 4209.44 ],
       [ 3473.494],
       [ 5688.656],
       [ 4470.538],
       [19492.92 ],
       [ 8686.556],
       [ 3371.114],
       [20525.1  ],
       [ 4192.088],
       [ 7260.032],
       [ 2369.7  ],
       [ 6197.118],
       [ 5896.418],
       [ 8204.53 ],
       [ 3749.25 ],
       [18127.22 ],
       [ 3009.476],
       [ 2542.822],
       [ 9740.06 ],
       [10498.28 ],
       [ 3942.664],
       [ 5116.52 ],
       [ 5584.278],
       [ 7206.196],
       [ 8541.41 ],
       [ 4425.382],
       [20675.32 ],
       [16225.92 ],
       [11239.778],
       [ 1928.76 ],
       [ 3322.244],
       [ 6171.372],
       [ 9120.65 ],
       [19701.72 ],
       [ 2047.9  ],
       [ 2158.45 ],
       [ 5455.378],
       [ 4059.418],
       [ 2894.608],
       [ 1890.616],
       [ 6088.05 ],
       [ 3206.754],
       [ 4523.818],
       [ 4339.646],
       [ 6554.05 ],
       [ 7812.278],
       [ 3519.954],
       [ 1785.232],
       [ 7506.83 ],
       [10934.008],
       [23348.26 ],
       [ 1778.718],
       [ 2764.408],
       [26078.5  ],
       [ 3423.584],
       [11986.406],
       [ 8209.62 ],
       [ 5679.032],
       [ 5289.564],
       [13786.36 ],
       [ 6996.148],
       [ 6160.712],
       [ 4232.644],
       [ 3597.316],
       [ 6684.734],
       [21145.66 ],
       [ 2328.216],
       [16629.48 ],
       [10522.514],
       [ 2143.906],
       [ 4199.69 ],
       [ 5455.614],
       [ 3883.52 ],
       [ 9924.684],
       [10137.99 ],
       [ 4972.78 ],
       [10185.69 ],
       [ 5591.846],
       [ 4307.29 ],
       [13919.22 ],
       [ 5340.04 ],
       [ 2085.68 ],
       [ 2524.748],
       [ 1920.816],
       [ 6785.558],
       [ 3013.46 ],
       [ 3243.192],
       [ 5239.026],
       [ 7418.21 ],
       [ 5316.426],
       [ 4733.68 ],
       [12188.4  ],
       [ 7380.22 ],
       [ 5092.238],
       [ 3755.378],
       [ 5003.364],
       [ 2892.016],
       [16147.1  ],
       [25818.32 ],
       [ 9535.22 ],
       [ 3939.7  ],
       [ 3039.466],
       [ 3541.73 ],
       [24096.92 ],
       [ 4177.182],
       [ 4288.914],
       [17111.44 ],
       [ 2274.686],
       [13693.08 ],
       [ 3131.378],
       [ 3747.76 ],
       [ 6642.476],
       [14570.3  ],
       [ 8952.212],
       [ 6255.576],
       [ 3606.214],
       [ 5787.538],
       [13950.02 ],
       [ 9350.832],
       [ 3048.852],
       [ 1394.232],
       [ 6915.688],
       [ 4461.84 ],
       [ 4316.984],
       [ 3818.464],
       [16552.96 ],
       [ 8406.224],
       [24937.752],
       [ 5885.042],
       [ 4285.866],
       [ 2050.552],
       [ 3059.334],
       [ 2374.654],
       [ 4729.998],
       [15232.42 ],
       [ 7167.176],
       [ 9137.102],
       [ 4860.898],
       [ 7516.97 ],
       [13321.36 ],
       [ 3671.212],
       [ 1738.828],
       [ 8674.146],
       [ 3989.516],
       [ 9027.69 ],
       [16244.98 ],
       [11966.28 ],
       [ 2360.266],
       [21298.74 ],
       [11585.3  ],
       [ 5547.948],
       [17694.64 ],
       [ 7130.51 ],
       [ 1727.968],
       [ 3168.07 ],
       [ 9419.32 ],
       [ 3274.806],
       [ 3867.838],
       [ 2551.594],
       [ 7431.258],
       [ 6775.954],
       [ 8890.92 ],
       [ 2897.512],
       [16884.5  ],
       [ 5175.856],
       [ 3226.986],
       [ 3108.528],
       [ 3655.108],
       [14329.5  ],
       [ 3916.828],
       [ 4348.854],
       [ 3577.938],
       [ 1776.062],
       [14749.94 ],
       [ 4970.478],
       [15163.234],
       [ 1784.824],
       [ 5523.804],
       [ 4305.088],
       [ 4301.06 ],
       [12818.16 ],
       [ 6894.664],
       [23674.14 ],
       [11035.026],
       [10103.48 ],
       [20047.114],
       [ 4743.47 ],
       [21267.688],
       [ 4802.32 ],
       [ 2323.312],
       [ 2043.49 ],
       [ 4189.726],
       [ 9132.364],
       [ 7632.358],
       [ 6045.032],
       [ 5451.892],
       [21570.5  ],
       [ 2301.042],
       [23453.938],
       [23020.1  ],
       [ 1910.128],
       [ 3541.322],
       [ 3917.888],
       [ 2845.238],
       [ 2007.782],
       [ 3792.204],
       [ 6136.644],
       [ 4393.744],
       [ 4252.566],
       [10859.52 ],
       [ 2475.444],
       [ 4375.702],
       [ 4330.41 ],
       [ 7909.286],
       [18809.246],
       [16966.54 ],
       [ 5452.61 ],
       [ 3708.26 ],
       [12974.26 ],
       [ 4279.47 ],
       [ 3183.514],
       [ 2126.464],
       [21700.7  ],
       [ 3779.   ],
       [ 5901.346],
       [ 3623.764],
       [ 9644.802],
       [ 1795.58 ],
       [ 2860.234],
       [ 2153.46 ],
       [ 4941.376],
       [ 3245.77 ],
       [17281.368],
       [ 1591.808],
       [17422.646],
       [25278.27 ],
       [ 8637.442],
       [ 4537.152],
       [ 3342.104],
       [11604.46 ],
       [ 1860.204],
       [15475.26 ],
       [ 2745.21 ],
       [ 3957.406],
       [13839.2  ],
       [18377.3  ],
       [15923.12 ],
       [ 4287.892],
       [ 1574.48 ],
       [13197.868],
       [17517.37 ],
       [ 6491.502],
       [ 2604.682],
       [ 3273.426],
       [ 3070.06 ],
       [17506.36 ],
       [13048.22 ],
       [ 5798.946],
       [ 3158.866],
       [ 6554.002],
       [ 3906.09 ],
       [12756.06 ],
       [ 3323.06 ],
       [ 2744.462],
       [ 4575.332],
       [21714.496],
       [ 4063.926],
       [ 3178.982],
       [ 5338.602],
       [ 7711.148],
       [ 8668.61 ],
       [ 3191.78 ],
       [ 3248.828],
       [ 4242.214],
       [13152.2  ],
       [ 3926.908],
       [ 3302.37 ],
       [ 2142.802],
       [ 3292.524],
       [ 5635.372],
       [ 2305.47 ],
       [ 2272.216],
       [26292.1  ],
       [ 2622.386],
       [ 3698.104],
       [ 3289.14 ],
       [16349.84 ],
       [ 6649.58 ],
       [ 9520.828],
       [ 4127.238],
       [ 5197.948],
       [11270.31 ],
       [ 2302.4  ],
       [19870.05 ],
       [ 6785.204],
       [ 3263.258],
       [ 6109.052],
       [ 3891.588],
       [ 6716.332],
       [ 5528.412],
       [ 2790.624],
       [ 7602.732],
       [ 1880.424],
       [ 3737.458],
       [ 2339.106],
       [ 7322.584],
       [ 3703.46 ],
       [ 2828.442],
       [11877.49 ],
       [ 9860.17 ],
       [ 2092.802],
       [ 8596.588],
       [11343.48 ],
       [ 3613.696],
       [20870.004],
       [ 4790.626],
       [ 3304.752],
       [ 3889.398],
       [11185.132],
       [20608.24 ],
       [ 2630.24 ],
       [ 8514.04 ],
       [ 1962.954],
       [ 3087.026],
       [ 1974.972],
       [ 4414.534],
       [ 3039.072],
       [ 6229.566],
       [ 2157.306],
       [ 2088.138],
       [ 5759.042],
       [16907.24 ],
       [ 1910.262],
       [ 7085.764],
       [13409.26 ],
       [ 5883.26 ],
       [25253.944],
       [ 4316.87 ],
       [14218.6  ],
       [ 7638.756],
       [ 6224.966],
       [ 1144.88 ],
       [ 4059.014],
       [ 3882.674],
       [ 3142.672],
       [10302.948],
       [ 1920.73 ],
       [21239.96 ],
       [ 5005.822],
       [ 1952.152],
       [ 3148.94 ],
       [ 5402.674],
       [ 4539.052],
       [ 2205.094],
       [ 7422.334],
       [ 6373.264],
       [21298.74 ],
       [ 2961.41 ],
       [ 3591.278],
       [16340.772],
       [ 4811.042],
       [ 5754.436],
       [ 4114.914],
       [15063.42 ],
       [ 6223.004],
       [ 3133.262],
       [ 1803.226],
       [16576.   ],
       [ 1851.056],
       [14162.008],
       [ 2324.476],
       [ 7693.936],
       [ 5196.944],
       [ 2400.306],
       [ 6237.324],
       [ 4273.434],
       [ 3465.97 ],
       [18038.66 ],
       [24702.66 ],
       [ 3962.798],
       [ 5002.74 ],
       [16028.82 ],
       [ 3341.926],
       [ 1863.702],
       [ 4972.78 ],
       [ 3979.606],
       [ 1207.478],
       [ 2083.034],
       [24536.58 ],
       [ 5569.322],
       [12058.74 ],
       [23836.28 ],
       [ 8087.938],
       [15715.02 ],
       [ 1779.876],
       [15542.84 ],
       [ 5569.708],
       [ 9196.89 ],
       [12890.02 ],
       [ 3150.444],
       [12612.62 ],
       [ 2454.658],
       [ 7833.512],
       [ 6750.498],
       [ 3555.928],
       [ 5176.74 ],
       [15485.62 ],
       [ 5654.68 ],
       [23176.82 ],
       [ 5681.126],
       [12155.974],
       [ 7286.524],
       [ 3477.01 ],
       [ 6022.066],
       [ 2654.838],
       [ 3559.792],
       [10371.318],
       [20264.22 ],
       [10556.194],
       [ 6364.886],
       [ 5289.564],
       [ 4492.654],
       [ 1918.2  ],
       [ 7129.342],
       [ 2911.66 ],
       [26474.68 ],
       [ 6880.124],
       [ 5239.578],
       [ 6164.732],
       [ 6877.52 ],
       [10223.224],
       [ 7037.3  ],
       [ 2437.56 ],
       [ 6691.378],
       [ 5001.076],
       [11069.12 ],
       [19538.16 ],
       [ 4437.378],
       [ 3481.702],
       [19116.4  ],
       [ 6834.758],
       [ 3875.214],
       [10435.782],
       [ 5937.31 ],
       [ 4008.152],
       [11504.882],
       [ 4634.154],
       [ 4928.244],
       [ 6782.48 ],
       [12129.294],
       [ 2168.5  ],
       [27611.368],
       [ 2590.29 ],
       [ 3242.176],
       [10786.164],
       [ 1951.366],
       [ 4171.344],
       [ 2053.364],
       [ 3425.764],
       [19776.52 ],
       [ 1596.86 ],
       [ 7498.116],
       [ 1962.   ],
       [ 2332.282],
       [ 8325.052],
       [ 2308.704],
       [ 5790.578],
       [ 9879.748],
       [ 5437.142]])

In [47]:
y_test

     annual_medical_cost
0                2128.24
1               24726.20
2                3958.81
3                1376.48
4               12182.14
..                   ...
995             14794.96
996               943.58
997              4242.47
998              6428.94
999              7464.00

[1000 rows x 1 columns]

## passing y_test and y_pred to evaluation metrics

In [65]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error
print('r2_score:',r2_score(y_pred,y_test))
print('MAE:',mean_absolute_error(y_pred,y_test))
print('MSE:',mean_squared_error(y_pred,y_test))
print('RMSE:',root_mean_squared_error(y_pred,y_test))

r2_score: 0.8145400496081621
MAE: 1797.3548768328528
MSE: 6342619.490979356
RMSE: 2518.45577506919

## saving the model

In [49]:
import joblib

joblib.dump({'model':model,'cat_encoder':OHE,'num_encoder':scaler},'medical_cost_prediction.pkl')

['medical_cost_prediction.pkl']

In [50]:
medical_cost =joblib.load('medical_cost_prediction.pkl')

In [51]:
medical_cost['model']

KNeighborsRegressor()

In [52]:
medical_cost['cat_encoder']

OneHotEncoder(sparse_output=False)

In [53]:
medical_cost['num_encoder']

MinMaxScaler()

In [54]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor

params = {
    'n_neighbors': [3,5,7,9,11,15],
    'weights': ['uniform','distance'],
    'metric': ['euclidean','manhattan']
}

grid = GridSearchCV(KNeighborsRegressor(),
                    params,
                    cv=5,
                    scoring='r2')

grid.fit(X_train_trans, y_train)

print(grid.best_params_)
print(grid.best_score_)

{'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'}
0.8667853545353488

In [55]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor(n_neighbors =7,metric='manhattan',weights='distance')

knn.fit(X_train_trans,y_train)

KNeighborsRegressor(metric='manhattan', n_neighbors=7, weights='distance')

In [56]:
y_pred = knn.predict(X_test_trans)

In [57]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.8145400496081621

## decision tree

In [58]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()

dt.fit(X_train_trans,y_train)

DecisionTreeRegressor()

In [59]:
y_pred_dt = dt.predict(X_test_trans)

In [60]:
y_pred_dt

array([ 1452.36, 26140.5 ,  4593.27,  1932.2 , 10452.91,  1053.3 ,
        1834.1 ,  2897.62,  5651.46, 23217.7 , 25987.  ,  3862.62,
        4672.83,  2491.84,  5826.43,  9834.55,  7117.46,  6501.04,
        7287.5 ,  4654.65,  5663.61,  4940.74, 10680.6 ,  7319.93,
       14892.94, 10145.09,  1753.11,  2344.26,  2469.26,  4975.68,
       20906.9 , 11828.72,  4564.58,  3461.61,  3810.06, 17131.9 ,
        1590.15,  4465.36,  6046.01, 12523.9 ,  4111.85, 14843.1 ,
       20426.8 ,  4203.81,  5282.33,  7273.58,  1739.01,   608.88,
       15576.2 ,  5161.22,  9264.55,  5482.38,  5575.77, 14428.3 ,
        4274.4 ,  2543.43, 18296.4 , 27008.8 ,  1995.22,  9147.29,
        8336.98,  4118.98,  6288.52, 11749.  ,  6517.05,  3823.29,
       23887.3 ,  9661.32,  8984.5 , 21340.5 , 17131.9 ,  8101.17,
        5318.27, 17131.9 ,  5840.48,  4605.85,  2840.1 ,  6175.12,
       13114.7 , 10072.4 , 13684.23, 31042.  ,  7821.99,  4445.54,
        5432.01, 25230.7 ,  5055.7 ,  1550.58, 19928.1 ,  8142.18,
        2388.96,  5432.01,  3815.18, 12679.  ,  5651.75, 27238.7 ,
       22569.3 ,  6076.2 , 13177.9 , 27008.8 ,  2871.33,  5004.16,
        1473.86,  2314.17, 10720.71,  3167.68,  5567.77,  4260.18,
       16456.8 ,  6241.14,  4299.88, 20906.9 , 12304.1 , 30451.5 ,
        1076.97,  2326.88, 26270.  ,  5652.95,  5137.36,  9934.18,
        6948.06, 21928.1 ,  4463.33,  9418.4 ,  7156.77,  6386.86,
        2749.16,  1447.91,  8609.1 , 18242.1 ,  2758.67,  5301.53,
        3451.8 , 12072.9 ,  4111.85,  8936.59,  3937.22,  8516.46,
        8445.17,   835.64,  5575.77, 16973.8 , 13740.7 ,  7124.2 ,
        4408.12,  9683.16,  4021.6 ,  3354.62,  5554.23,  1495.16,
        4277.9 ,  2972.22,  4099.48,  6119.02,  2451.82,  5835.31,
       10670.3 ,  4299.88,  3532.45,  2184.06,  1250.66,  6407.82,
        4445.28,  5641.18,  7642.78,  3531.18,  2390.88,  1993.54,
       11531.31, 21200.7 , 23990.6 ,  5534.57,  2502.78, 10796.15,
        6532.62,  3553.53,  7317.32,  4646.49,  2371.11,  6165.38,
        3858.6 ,  3732.  ,  5180.68,  7428.09, 22301.3 ,  3261.6 ,
        4561.34,  5328.15,  4672.56,  5612.99,  2692.15,  7317.32,
        6440.28, 12834.1 ,  6390.82,  6681.06,  3399.17,   608.88,
        5293.89,  7315.28,  5180.68, 27321.1 ,  5389.19,  1839.1 ,
        2371.11, 14883.6 ,  2641.14, 16973.8 ,  2325.88,  2200.74,
        7134.36, 10582.49,  5512.26,  8976.52,  5558.87,  3792.7 ,
        5567.77,  3464.5 ,  2355.53, 17969.1 ,  2987.28,  1209.26,
        3619.64,  6472.  ,  6202.03,  8250.26,  1839.1 ,  5951.67,
        8720.04,  3907.54, 27941.2 ,  4514.51,  1753.11,  2978.88,
        3070.17,  1327.56,  4116.68,  1206.64, 16433.3 ,  2646.57,
        5469.39,  9879.2 ,  4465.53,  3929.41,  2118.35,  2932.64,
        5593.26,  6734.72,  3014.42,  2778.08,  2543.43, 13684.23,
        3989.75, 19199.2 ,  4334.4 , 16060.39,  3749.77, 22227.4 ,
        2226.12, 10884.98,  4103.75,  4466.4 ,  8336.98,  1371.65,
       17372.7 ,  5472.53,  1651.46,  3528.87,  1211.27,  4392.12,
       13197.  ,  2296.6 ,  6525.28, 24971.6 ,  1839.1 , 19799.8 ,
        3094.22,  8064.29,  2541.38,  8006.9 ,  5809.64, 10767.12,
        3629.54, 22317.7 ,  1335.47,  5167.46,  2384.99, 20797.1 ,
        4312.56,  6158.13,  7136.38,  3690.86,  7317.32, 17224.2 ,
        1738.27,  1186.16,  3900.6 , 12679.  ,  3489.56, 18142.5 ,
        3985.5 ,  2068.9 , 19574.4 , 23586.1 ,  3921.5 ,  6798.12,
        7864.1 ,  3263.47,  5529.  ,  9044.93,  5267.36,  2404.16,
        8577.74,  2312.14,  8519.56,  1559.38,  1540.9 , 16513.4 ,
       10680.6 ,  2230.85, 15332.4 ,  3807.08, 19106.1 ,  2692.15,
        4445.54,  2848.23,  8069.3 ,  1142.84,  2598.75,  1874.04,
        3873.66,  5440.54,  4111.85,  3247.73,  4465.53, 26255.6 ,
        4799.  ,  4306.82,  1353.49, 12255.83,  3638.72, 15574.5 ,
        5957.06, 22301.3 ,  1651.46,  7136.38,  7328.45,  7845.6 ,
        2792.92,  2491.84,  3109.73,  9565.55,  1648.29,  4175.37,
       10739.75, 11424.95,  5161.22,  1894.62, 10985.67,  3915.22,
       18806.5 ,  4432.14,  1452.62, 12355.88, 23282.7 ,   667.41,
        6725.16,   806.38,  6681.06, 23217.7 , 11201.15,  4677.68,
       14721.9 , 21527.5 ,  3436.27, 17265.7 ,  9143.2 ,  7315.28,
        3938.59,  1248.26,  6878.69,  8339.25,  1473.1 ,  3726.37,
        5612.99,  9334.87,  7924.86,  3583.04,  5390.38,  6319.26,
       11885.68,  4280.85,  6248.02,  5061.9 ,  1817.99,  2595.02,
        1945.76,  7134.36,  3059.32,  4118.98,  1842.39,  5198.88,
        3016.43, 26235.3 ,  1442.17, 25230.7 , 16973.8 ,  3637.41,
        9488.31,  9718.41, 14511.89, 19215.8 ,  6878.69,  9409.54,
       12336.34,  5160.74, 12402.99,  3193.7 ,  5139.3 ,  6390.82,
        2402.67,  3711.42, 10956.7 ,  3364.07,  1137.24,   856.58,
       25285.6 , 11412.93, 14619.9 ,  5730.05,  4605.85,  3633.02,
       27728.8 ,  5826.43, 14973.  ,  2407.39,  8042.58,  5180.68,
       13493.  ,  2563.85,  2443.52, 22079.5 ,  1353.56,  1467.49,
        2824.33,  6276.36,  2759.92,  1753.11, 23976.3 ,  4560.69,
       10081.5 , 25230.7 ,  6428.19,  3695.26,  3362.46,  6205.67,
       10383.07,  1479.57,  8036.42,  2930.93,  4398.11, 21238.5 ,
        3270.21,  5248.42,  7150.33, 40883.6 ,  3464.5 ,  8983.15,
        5075.52,  2662.4 , 28510.7 , 19800.5 , 18838.2 ,  1374.87,
        3270.88, 18543.7 ,  4000.44,  4977.66,  7048.99,  4067.3 ,
       25161.9 , 18280.6 ,  3531.18,  5883.8 ,  2517.72,  3635.65,
        4445.28,  4058.42, 23381.  ,  1310.27, 11732.  ,  4842.23,
        5055.62,  6253.02,  2730.1 ,  3972.32,  3879.67,  1855.49,
        1916.07,  6468.94,  3362.46,  4671.97, 14090.2 ,  6476.72,
        2704.23,  1618.84,  5880.22, 20261.8 ,  2342.95,  1632.39,
        2401.94,  2646.57,  6386.86,  2371.11,  5110.84,  2324.63,
        5252.16,  4457.3 ,  6846.88, 10144.48,  1721.71,  2457.83,
        6214.49,  1416.53,  4232.01,  5115.12,  2318.58, 15653.2 ,
       11692.4 , 19574.4 ,  6102.68,  3670.35,  2309.29,  8233.84,
        6432.37, 18673.4 , 12891.95,  5099.  , 21456.8 ,  6241.14,
        3197.97,  2470.61,  5863.54,  5738.27,  5660.36,  5683.78,
       16973.8 ,  3094.22,  1589.47, 10935.1 ,  8069.3 ,  4890.21,
        3875.17,  4326.62, 10884.98,  7287.93,  5242.03, 26711.1 ,
       15821.6 , 11042.72,  3138.77,  2191.04,  7135.68, 10037.75,
       19360.5 ,  2045.22,  1589.47,  2469.26,  3423.96,  3991.25,
        3757.18,  5999.58,  1917.43,  3882.93,  5441.88,  4176.35,
        9488.31,  2003.28,  1477.87,  3690.86, 14511.89, 29901.4 ,
        1711.09,  4356.46, 29929.4 ,  2072.97,  2116.72, 11016.77,
        7070.27,  5282.33, 12022.6 ,  8832.1 ,  7691.97,  1558.65,
        5180.68,  6548.04, 26017.8 ,  3703.32, 18242.1 ,  8758.16,
        1060.  ,  5267.36,  5575.77,  7278.41, 10987.49, 10553.88,
        3808.9 , 11609.31,  5417.79,  4362.19, 18099.  ,  7562.42,
        3859.42,  4565.48,  1550.58,  5880.22,  1353.05,  2692.15,
        3833.25,  4604.71,  6753.15,  3073.87,  7375.2 ,  9150.9 ,
        4592.83,  3882.93,  5175.72,  3059.32, 15255.8 , 27922.4 ,
        7089.  ,   947.87,  2280.38,  5929.1 , 23887.3 ,  2312.14,
        5509.12, 16424.7 ,  4301.72, 12834.1 ,  4624.72,  3489.56,
        6124.58, 16334.3 ,  8129.65,  5568.25,  5629.25,  7319.22,
        9143.2 ,  8108.8 ,  3190.24,  2304.39,  9756.8 ,  4175.3 ,
        2182.66,  8036.42, 22855.6 ,  9334.87, 26235.3 ,  4382.71,
        4218.84,  1185.24,  4017.83,  1874.04,  1721.71, 13628.3 ,
        4301.06,  7752.38,  6262.95,  8356.91,  7375.2 ,  3668.44,
         856.58,  7209.14,  7175.52, 11943.42, 16433.3 ,  9025.3 ,
        2792.92, 19186.1 , 14593.32,  1211.27, 14308.6 ,  4371.77,
        2470.61,  2565.14,  6472.  ,  1776.17,  4244.53,  2040.36,
        6607.59,  2946.58,  8069.3 ,  1353.49, 17731.8 , 11607.68,
        2839.05,  4752.64,  2987.28, 22855.6 ,  5951.67,  4528.4 ,
        1379.59,  1630.81, 21456.8 ,  6205.67, 16514.2 ,  2408.42,
        6969.74,  4230.53,  3619.64,  7375.2 ,  3555.93, 28921.  ,
       13463.23,  8440.1 , 20906.9 ,  8404.87, 26270.  ,  2031.86,
        6614.71,  2840.1 ,  4677.68,  8981.36,  7660.73,  4638.53,
        8620.05, 26709.9 ,  5025.48, 19800.5 , 25702.8 ,  2729.52,
        6552.82,  4382.71,  2878.77,  2113.56,  3147.02,  8981.36,
        4874.05,  4038.1 , 16334.3 ,  6501.04,  5160.74,  7563.21,
        3555.93, 27238.7 , 30563.9 , 10910.81,  5479.53, 10680.6 ,
        1754.92,  1999.35,  1938.34, 17783.6 ,  3792.7 ,  4671.97,
        1430.93,  9424.22,  4293.02,  2924.4 ,  2470.61,  2118.35,
        2813.82, 15925.49,   608.88, 23302.4 , 26711.1 ,  5999.58,
        5170.46,  1999.11,  8760.  ,  1276.14, 12679.  ,  3815.18,
        7071.78, 12235.7 , 15812.3 , 17783.6 ,  3038.61,  2258.05,
       17596.61, 20467.7 ,  7858.18,  1382.  ,  2813.82,  2942.08,
       15117.2 , 20771.6 ,  6102.68,  2234.67,  7162.2 ,  5506.07,
       20095.8 ,  8779.48,  1731.26,  4203.81, 22433.5 ,  6740.5 ,
        2390.88,  5387.98, 12357.02,  9512.72,  2972.22,  4656.12,
        6652.38,  9143.2 ,  7317.32,   667.41,  1353.49,  8382.09,
        1812.81,  3438.64,  1574.7 , 31733.2 ,  1688.3 ,  2256.19,
         968.16,  8760.  ,  6256.99,  7983.2 ,  2892.79,  4101.67,
       16429.4 ,  5402.32, 23284.1 ,  9989.85,  5110.84,  8519.56,
        3859.42,  5115.12,  4238.61,   667.41, 12355.88,  4231.78,
        5593.92,  4869.77,  5207.47,  6256.99,  2715.95, 11597.32,
        8760.  ,  2196.41, 11180.2 , 14202.5 ,  1978.59, 21456.8 ,
        8220.65,  3086.82,  4566.21,  8605.2 , 21396.9 ,  2261.65,
        9270.8 ,  1817.99,  3221.88,  1682.51,  4592.55,  6358.53,
       13652.94,  2622.91,  1618.84,  8613.41, 17074.7 ,  2264.62,
        4466.4 , 16335.9 ,  1754.92, 29929.4 ,  3371.56, 12608.8 ,
        7105.53, 10028.95,  2234.67,  4000.44,  5681.6 ,  1416.53,
       14197.01,  1746.87, 27549.9 ,  3413.65,  1250.66,  4987.2 ,
       11412.93,  7924.86,  2476.2 ,  8620.05,  3464.5 , 21520.3 ,
        6309.62,  4021.84, 22547.3 ,  3938.59,  6407.82,  4902.94,
       16142.4 ,  9570.58,  2402.67,  3789.86, 18543.7 ,  1837.64,
       22651.7 ,   738.89, 11609.31, 10113.8 ,  2990.02, 10072.4 ,
        2540.75,  4490.13, 17265.7 , 24608.5 ,  3798.68,  1381.57,
       15784.8 ,  1297.06,  1685.71,  4559.84,  6534.14,  1992.07,
        1185.24, 25285.6 ,  4445.54, 11170.4 , 23251.3 ,  9963.76,
       16472.3 ,  2388.96, 27294.1 , 10388.4 ,  6688.78, 12777.3 ,
        4229.29, 15576.2 ,  2971.88,  5261.21,  8404.87,  5106.48,
        7124.2 , 16340.5 ,  4116.68, 19360.5 ,  7194.1 , 14865.2 ,
        6725.16,  3175.24,  5094.26,  2402.67,  4432.14, 11405.42,
       13445.9 , 10043.75,  6534.16,  5306.78,  2779.5 ,  3456.79,
        7427.89,  1473.86, 22433.5 ,  6753.15,  5267.2 ,  5797.37,
        5797.37, 14593.32,  8144.6 ,  2785.46, 12845.1 ,  4051.8 ,
       14317.45, 21238.5 ,  4216.42,  7056.27, 19774.1 ,  6698.22,
        2806.59,  6264.88,  6248.02,  2517.72,  9565.55,  6534.16,
        1935.05,  6166.69, 17062.83,  1685.71, 35182.  ,  1934.24,
        1379.59,  6171.14,  1738.27,  7019.1 ,   404.95,  3582.56,
       25246.3 ,  3086.82,  6921.17,  2252.73,  2455.02, 12251.58,
         709.58,  5886.63,  6974.88,  6910.93])

In [61]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred_dt)

0.9542706000714547

## hyperparameter tuning

In [62]:
from sklearn.model_selection import GridSearchCV

"""params = {
    "criterion": ["squared_error", "friedman_mse", "absolute_error"],
    
    "max_depth": [None, 3, 5, 10, 15, 20],
    
    "min_samples_split": [2, 5, 10, 20],
    
    "min_samples_leaf": [1, 2, 5, 10],
    
    "max_features": [None, "sqrt", "log2"],
    
    "max_leaf_nodes": [None, 10, 20, 50, 100],
    
    "ccp_alpha": [0.0, 0.001, 0.01, 0.1]
}

grid = GridSearchCV(DecisionTreeRegressor(),
                    param_grid =params,
                    cv= 5,
                    scoring = 'r2')

grid.fit(X_train_trans,y_train)"""

'params = {\n    "criterion": ["squared_error", "friedman_mse", "absolute_error"],\n    \n    "max_depth": [None, 3, 5, 10, 15, 20],\n    \n    "min_samples_split": [2, 5, 10, 20],\n    \n    "min_samples_leaf": [1, 2, 5, 10],\n    \n    "max_features": [None, "sqrt", "log2"],\n    \n    "max_leaf_nodes": [None, 10, 20, 50, 100],\n    \n    "ccp_alpha": [0.0, 0.001, 0.01, 0.1]\n}\n\ngrid = GridSearchCV(DecisionTreeRegressor(),\n                    param_grid =params,\n                    cv= 5,\n                    scoring = \'r2\')\n\ngrid.fit(X_train_trans,y_train)'

In [63]:
#print(grid.best_params_)
#print(grid.best_score_)
#print(grid.best_estimator_)

In [64]:
from sklearn import tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))
tree.plot_tree(
    grid.best_estimator_,   # or your trained model
    feature_names=X_train_trans.columns if hasattr(X_train_trans, "columns") else None,
    class_names=True,
    filled=True
)

plt.show()

InvalidParameterError: The 'decision_tree' parameter of plot_tree must be an instance of 'sklearn.tree._classes.DecisionTreeClassifier' or an instance of 'sklearn.tree._classes.DecisionTreeRegressor'. Got KNeighborsRegressor(metric='manhattan', n_neighbors=7, weights='distance') instead.

In [ ]:
train_score_dt = dt.score(X_train_trans,y_train.values.ravel())
print(train_score_dt)

In [ ]:
test_score_dt = dt.score(X_test_trans,y_test.values.ravel())
print(test_score_dt)

## linear regression

In [ ]:
from sklearn.linear_model import LinearRegression 

LR = LinearRegression()

LR.fit(X_train_trans,y_train)

In [ ]:
from sklearn.metrics import r2_score

y_pred_lr = LR.predict(X_test_trans)

score = r2_score(y_pred,y_test)
score

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

params = {
    'alpha': [0.001, 0.01, 0.1, 1, 10, 100]
}

grid = GridSearchCV(
    Ridge(),
    param_grid=params,
    cv=5,
    scoring='r2'
)

grid.fit(X_train_trans, y_train)

print(grid.best_params_)
print(grid.best_score_)

In [ ]:
#pip install mlxtend

In [ ]:
from mlxtend.evaluate import bias_variance_decomp

In [ ]:
avg_expected_loss,avg_bias,avg_var = bias_variance_decomp(LR,X_train_trans,y_train.values.ravel(),X_test_trans,y_test.values.ravel(),loss = 'mse')

In [ ]:
print(avg_expected_loss)
print(avg_bias)
print(avg_var)

In [ ]:
train_score = LR.score(X_train_trans,y_train)
print(train_score)

In [ ]:
test_score = LR.score(X_test_trans,y_test)
print(test_score)

## Lasso regularization

In [ ]:
from sklearn.linear_model import Lasso

lasso = Lasso(alpha =1)

lasso.fit(X_train_trans,y_train)

In [ ]:
lasso.coef_

In [ ]:
import pandas as pd

coef = pd.Series(lasso.coef_, index=X_train_trans.columns)

print(coef)
print("Features removed:", (coef == 0).sum())

In [ ]:
import numpy as np
print(np.count_nonzero(lasso.coef_))

In [ ]:
X_train_trans = X_train_trans.to_numpy()

In [ ]:

selected_features = X_train_trans[lasso.coef_[0] !=0]
print(selected_features)

In [ ]:
from sklearn.metrics import r2_score

y_pred_1 = lasso.predict(X_test_trans)

lasso_score= r2_score(y_pred_1,y_test)

In [ ]:
lasso_score

In [ ]:
from sklearn.linear_model import Lasso

lasso_1 = Lasso(alpha =0.001)

lasso_1.fit(X_train_trans,y_train)

In [ ]:
from sklearn.metrics import r2_score

y_pred = lasso_1.predict(X_test_trans)

lasso_score= r2_score(y_pred,y_test)

In [ ]:
lasso_score

In [ ]:
from sklearn.linear_model import LassoCV-

lasso_cv = LassoCV(alphas = 100,
                   cv=5,
                   random_state = 42)
                   
lasso_cv.fit(X_train_trans,y_train)

In [ ]:
print(lasso_cv.alpha_)

In [ ]:
from sklearn.linear_model import Lasso

lasso_5 = Lasso(alpha =lasso_cv.alpha_)

lasso_5.fit(X_train_trans,y_train)

In [ ]:
from sklearn.metrics import r2_score

y_pred = lasso_5.predict(X_test_trans)

lasso_score= r2_score(y_pred,y_test)

In [ ]:
lasso_score

## elastic net

In [ ]:
from sklearn.linear_model import ElasticNet

elastic =  ElasticNet(alpha = 0.1)
elastic.fit(X_train_trans,y_train)

In [ ]:
from sklearn.metrics import r2_score

y_pred_2 = elastic.predict(X_test_trans)

elastic_score= r2_score(y_test, y_pred_2)

print("R² Score:", elastic_score)

In [ ]:
from sklearn.linear_model import ElasticNet

elastic_1 =  ElasticNet(alpha = 0.1,l1_ratio =0.5)
elastic_1.fit(X_train_trans,y_train)

In [ ]:
from sklearn.metrics import r2_score

y_pred_3 = elastic_1.predict(X_test_trans)

elastic_score_1= r2_score(y_test, y_pred_2)

print("R² Score:", elastic_score_1)

## feature selection

In [ ]:
from sklearn.feature_selection import f_oneway,SelectKBest,f_regression,chi2

kbest = SelectKBest(f_regression,k=15)

In [ ]:
kbest.fit_transform(X_train_trans,y_train)

In [ ]:
kbest.get_feature_names_out()

In [ ]:
selected_columns = X_train.columns[kbest.get_support()]  
print(selected_columns)