In [152]:
import pandas as pd
import numpy as np
import sklearn

In [153]:
df = pd.read_csv('medical_cost_prediction_dataset.csv')
df.head()

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost,annual_medical_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885,2645.50
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722,10959.70
2,89,Male,25.7,No,0,0,0,0,High,10578,4.5,7,2,0,3,NaN,0,Urban,4196,8409.80
3,78,Male,31.9,Yes,0,1,0,0,Low,6226,8.6,9,6,1,7,Government,70,Urban,11128,7996.62
4,38,Male,27.7,No,0,0,0,0,High,6253,5.7,3,6,0,6,Private,77,Urban,15110,3202.52

In [154]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   str
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   str
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   str
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           3952 non-null   str
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   str
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), str(5)
memory usage: 903.4 KB

In [155]:
df.duplicated().sum()

np.int64(0)

In [156]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
smoker                        0
diabetes                      0
hypertension                  0
heart_disease                 0
asthma                        0
physical_activity_level       0
daily_steps                   0
sleep_hours                   0
stress_level                  0
doctor_visits_per_year        0
hospital_admissions           0
medication_count              0
insurance_type             1048
insurance_coverage_pct        0
city_type                     0
previous_year_cost            0
annual_medical_cost           0
dtype: int64

In [157]:
df.columns

Index(['age', 'gender', 'bmi', 'smoker', 'diabetes', 'hypertension',
       'heart_disease', 'asthma', 'physical_activity_level', 'daily_steps',
       'sleep_hours', 'stress_level', 'doctor_visits_per_year',
       'hospital_admissions', 'medication_count', 'insurance_type',
       'insurance_coverage_pct', 'city_type', 'previous_year_cost',
       'annual_medical_cost'],
      dtype='str')

In [158]:
df['insurance_type'] = df['insurance_type'].fillna('unknown')

In [159]:
df.isnull().sum()

age                        0
gender                     0
bmi                        0
smoker                     0
diabetes                   0
hypertension               0
heart_disease              0
asthma                     0
physical_activity_level    0
daily_steps                0
sleep_hours                0
stress_level               0
doctor_visits_per_year     0
hospital_admissions        0
medication_count           0
insurance_type             0
insurance_coverage_pct     0
city_type                  0
previous_year_cost         0
annual_medical_cost        0
dtype: int64

In [160]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      5000 non-null   int64
 1   gender                   5000 non-null   str
 2   bmi                      5000 non-null   float64
 3   smoker                   5000 non-null   str
 4   diabetes                 5000 non-null   int64
 5   hypertension             5000 non-null   int64
 6   heart_disease            5000 non-null   int64
 7   asthma                   5000 non-null   int64
 8   physical_activity_level  5000 non-null   str
 9   daily_steps              5000 non-null   int64
 10  sleep_hours              5000 non-null   float64
 11  stress_level             5000 non-null   int64
 12  doctor_visits_per_year   5000 non-null   int64
 13  hospital_admissions      5000 non-null   int64
 14  medication_count         5000 non-null   int64
 15  insurance_type           5000 non-null   str
 16  insurance_coverage_pct   5000 non-null   int64
 17  city_type                5000 non-null   str
 18  previous_year_cost       5000 non-null   int64
 19  annual_medical_cost      5000 non-null   float64
dtypes: float64(3), int64(12), str(5)
memory usage: 910.0 KB

In [161]:
for i in df.columns:
    print('*'*20,i,'*'*20)
    print(df[i].unique())
    print()

******************** age ********************
[69 32 89 78 38 41 20 39 70 19 47 55 81 77 50 75 66 76 59 79 64 68 72 24
 56 35 21 31 26 88 61 25 52 53 67 23 71 80 51 65 57 43 58 46 62 82 18 28
 22 45 29 40 54 44 60 30 49 83 74 87 73 36 85 34 86 33 37 84 48 42 63 27]

******************** gender ********************
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

******************** bmi ********************
[29.4 22.9 25.7 31.9 27.7 23.  22.8 21.7 23.3 29.8 24.9 19.3 34.8 27.6
 19.  23.8 26.6 34.5 20.5 30.9 33.  24.6 20.8 25.  25.8 29.3 31.5 22.3
 16.2 25.9 27.5 27.2 24.4 33.6 27.9 24.1 23.5 25.2 34.2 25.1 23.6 35.8
 28.3 26.4 26.2 14.1 29.7 26.7 28.1 22.4 23.9 31.1 36.4 28.2 19.6 25.4
 22.7 15.  34.  29.5 28.7 26.8 19.1 30.2 20.7 13.3 25.3 29.6 29.2 27.3
 32.  18.4 28.5 29.1 19.8 18.5 31.6 26.1 32.5 32.6 27.1 38.5 24.2 30.8
 34.4 34.3 32.1 17.6 36.2 21.1 28.  18.7 31.2 29.9 31.4 27.4 21.  26.
 24.3 27.  35.5 31.8 12.3 33.7 23.2 24.7 22.2 17.3 25.5 30.5 26.5 23.4
 13.2 17.1 21.3 28.4 34.6 21.9 27.8 30.3 22.1 11.8 32.8 33.8 33.2 30.7
 21.6 22.  32.9 22.6 21.4 18.6 18.8 32.7 40.1 19.4 26.9 21.2 32.3 19.7
 26.3 28.6 24.  15.6 28.8 16.5 19.9 24.8 23.1 28.9 33.1 17.2 19.2 25.6
 17.9 35.4 21.8 19.5 36.5 29.  35.7 13.5 41.5 35.1 14.5 39.5 13.8 20.4
 30.1 20.  15.4 40.6 17.  14.9 24.5 32.2 22.5 32.4 14.  14.7 31.  18.1
 13.4 31.3 21.5 11.5 30.  16.6 14.4 37.2 18.3 17.7 36.3 15.2 34.1 36.
 20.1 31.7 36.9 17.8 18.9 17.5 37.  33.5 39.2 37.9 20.3 37.7 35.3 18.2
 30.4 33.9 17.4 20.6 12.4 37.5 20.2 13.6 30.6 33.3 16.3 37.6 39.9 36.7
 16.1 34.9 18.  33.4 23.7 12.9 16.9 15.9 20.9 12.5 12.6 16.8 34.7 37.8
 15.8 35.  40.7 14.2 15.5 35.2 38.2 38.6 43.6 38.8 39.3 35.6 14.6 39.6
  9.9 12.7 15.7 36.6 41.6 16.4 38.3 35.9 11.2 10.8 37.4 40.  14.8 12.1
 38.   7.6 15.3  8.  39.  11.7 40.3 38.1 36.8 10.3 37.3 41.   9.8  6.8
 42.9 11.3 37.1 38.9 41.8 16.  36.1 39.8 16.7 12.  38.7  6.4 14.3 13.7]

******************** smoker ********************
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

******************** diabetes ********************
[1 0]

******************** hypertension ********************
[0 1]

******************** heart_disease ********************
[0 1]

******************** asthma ********************
[0 1]

******************** physical_activity_level ********************
<ArrowStringArray>
['Medium', 'High', 'Low']
Length: 3, dtype: str

******************** daily_steps ********************
[14825  3620 10578 ...  1517  8379  2000]

******************** sleep_hours ********************
[4.4 6.  4.5 8.6 5.7 7.7 4.6 7.4 8.2 5.  6.1 7.1 8.  6.7 8.4 8.3 6.9 9.
 6.4 7.9 4.7 8.9 5.8 5.1 5.4 4.3 6.5 5.9 5.5 6.8 6.3 5.2 7.8 8.8 6.2 7.
 4.1 7.6 8.7 7.2 8.1 8.5 7.5 4.  4.2 4.9 5.3 5.6 6.6 4.8 7.3]

******************** stress_level ********************
[ 8  7  9  3 10  6  4  1  5  2]

******************** doctor_visits_per_year ********************
[ 1  4  2  6  5  3  8  0  7 12  9 11 13 10 14]

******************** hospital_admissions ********************
[0 3 1 2 4 5 6]

******************** medication_count ********************
[4 0 3 7 6 2 1 5]

******************** insurance_type ********************
<ArrowStringArray>
['Private', 'Government', 'unknown']
Length: 3, dtype: str

******************** insurance_coverage_pct ********************
[80 64  0 70 77 89 71 66 54 50 82 63 52 51 72 83 53 78 62 69 87 93 61 67
 73 79 68 59 88 56 90 65 55 58 57 76 92 81 74 75 84 94 60 85 91 86]

******************** city_type ********************
<ArrowStringArray>
['Semi-Urban', 'Urban', 'Rural']
Length: 3, dtype: str

******************** previous_year_cost ********************
[10885 18722  4196 ... 16543 11310 17078]

******************** annual_medical_cost ********************
[ 2645.5  10959.7   8409.8  ...  3354.62  1401.72  6548.04]

In [162]:
X=df.drop('annual_medical_cost',axis=1)
y=df[['annual_medical_cost']]

In [163]:
X

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
0,69,Male,29.4,No,1,0,0,0,Medium,14825,4.4,8,1,0,4,Private,80,Semi-Urban,10885
1,32,Female,22.9,No,1,0,0,0,Medium,3620,6.0,7,4,3,0,Government,64,Semi-Urban,18722
2,89,Male,25.7,No,0,0,0,0,High,10578,4.5,7,2,0,3,unknown,0,Urban,4196
3,78,Male,31.9,Yes,0,1,0,0,Low,6226,8.6,9,6,1,7,Government,70,Urban,11128
4,38,Male,27.7,No,0,0,0,0,High,6253,5.7,3,6,0,6,Private,77,Urban,15110
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,77,Female,19.7,Yes,0,0,0,0,Low,7825,5.7,3,3,0,4,Government,77,Semi-Urban,17154
4996,43,Female,23.9,Yes,0,0,0,0,Medium,9054,8.4,7,4,0,1,unknown,0,Urban,4797
4997,58,Female,31.1,No,0,0,0,0,Medium,6299,6.7,3,6,1,2,Private,81,Semi-Urban,16543
4998,53,Male,27.6,No,0,0,0,0,Medium,8379,6.2,8,4,0,4,Private,88,Urban,11310
4999,40,Male,25.8,No,0,0,0,0,Low,2000,5.3,5,2,1,4,Government,63,Urban,17078

In [164]:
y

      annual_medical_cost
0                 2645.50
1                10959.70
2                 8409.80
3                 7996.62
4                 3202.52
...                   ...
4995              3513.76
4996              9816.10
4997              3354.62
4998              1401.72
4999              6548.04

[5000 rows x 1 columns]

In [165]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size =0.8,random_state=42)

In [166]:
X_train

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
4227,73,Male,27.4,No,0,0,0,0,High,2806,6.6,9,1,1,6,Private,79,Urban,11798
4676,53,Female,22.5,No,0,0,1,0,Low,6800,4.5,9,7,0,4,Private,78,Semi-Urban,5956
800,52,Female,24.9,No,0,1,0,0,High,7567,8.0,5,7,2,6,Private,85,Semi-Urban,14943
3671,49,Male,24.3,No,1,0,1,0,Medium,11050,8.1,5,4,0,5,Government,64,Semi-Urban,6355
4193,40,Male,38.0,No,0,0,0,0,Medium,3463,6.9,7,3,1,2,Private,80,Urban,19822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4426,60,Male,29.0,No,0,0,0,0,Medium,1898,8.9,5,3,1,2,unknown,0,Semi-Urban,6929
466,33,Female,25.6,No,0,0,0,0,High,12035,8.4,5,3,1,7,Private,85,Urban,19576
3092,64,Female,24.4,Yes,0,1,1,0,Medium,10186,6.5,3,7,1,0,Government,76,Urban,9218
3772,21,Female,31.3,No,0,0,0,0,Low,2878,4.9,2,7,1,2,Government,62,Urban,859
860,74,Male,20.0,No,0,0,1,0,Low,2959,8.6,2,6,1,1,unknown,0,Semi-Urban,19631

In [167]:
for i in [X_train,X_test,y_train,y_test]:
    i.reset_index(drop=True,inplace=True)

In [168]:
X_train

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
0,73,Male,27.4,No,0,0,0,0,High,2806,6.6,9,1,1,6,Private,79,Urban,11798
1,53,Female,22.5,No,0,0,1,0,Low,6800,4.5,9,7,0,4,Private,78,Semi-Urban,5956
2,52,Female,24.9,No,0,1,0,0,High,7567,8.0,5,7,2,6,Private,85,Semi-Urban,14943
3,49,Male,24.3,No,1,0,1,0,Medium,11050,8.1,5,4,0,5,Government,64,Semi-Urban,6355
4,40,Male,38.0,No,0,0,0,0,Medium,3463,6.9,7,3,1,2,Private,80,Urban,19822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,60,Male,29.0,No,0,0,0,0,Medium,1898,8.9,5,3,1,2,unknown,0,Semi-Urban,6929
3996,33,Female,25.6,No,0,0,0,0,High,12035,8.4,5,3,1,7,Private,85,Urban,19576
3997,64,Female,24.4,Yes,0,1,1,0,Medium,10186,6.5,3,7,1,0,Government,76,Urban,9218
3998,21,Female,31.3,No,0,0,0,0,Low,2878,4.9,2,7,1,2,Government,62,Urban,859
3999,74,Male,20.0,No,0,0,1,0,Low,2959,8.6,2,6,1,1,unknown,0,Semi-Urban,19631

In [169]:
X_test

,age,gender,bmi,smoker,diabetes,hypertension,heart_disease,asthma,physical_activity_level,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,hospital_admissions,medication_count,insurance_type,insurance_coverage_pct,city_type,previous_year_cost
0,36,Male,28.4,No,0,0,0,0,Low,3701,5.5,2,5,0,0,Government,65,Urban,7029
1,39,Male,14.1,No,0,0,0,0,High,3051,4.2,4,4,3,1,unknown,0,Semi-Urban,7744
2,86,Female,24.7,No,0,0,0,0,Medium,2059,6.8,1,2,1,3,Private,72,Rural,7592
3,39,Female,32.6,No,0,0,0,0,Low,8737,6.7,9,5,2,0,Private,93,Semi-Urban,7020
4,40,Female,30.8,Yes,0,0,0,0,Low,10271,6.6,3,4,2,1,Government,51,Urban,17125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,60,Male,31.6,Yes,1,1,0,0,Low,3368,7.7,1,4,3,0,Government,56,Urban,13923
996,78,Male,27.5,No,0,0,0,0,Low,5133,5.8,6,2,0,2,Private,92,Urban,19366
997,26,Male,27.2,No,0,1,0,0,Low,2559,5.8,3,5,0,6,Government,62,Urban,1428
998,54,Male,34.7,Yes,0,0,0,0,High,5031,7.8,3,3,3,1,Government,79,Urban,16310
999,31,Male,22.2,No,0,0,0,0,High,4234,8.4,6,1,3,5,Private,74,Semi-Urban,12739

In [170]:
y_train

      annual_medical_cost
0                 3952.49
1                 3590.80
2                 4330.49
3                 6377.58
4                 3617.32
...                   ...
3995             13948.70
3996              3165.12
3997              5802.58
3998              4718.35
3999             22569.30

[4000 rows x 1 columns]

In [171]:
cat_train=X_train.select_dtypes(include='object')

num_train = X_train[['age','bmi','daily_steps','sleep_hours','stress_level','doctor_visits_per_year','insurance_coverage_pct','previous_year_cost']]

no_train = X_train[['diabetes','hypertension','heart_disease','asthma','hospital_admissions','medication_count']]

C:\Users\kavya\AppData\Local\Temp\ipykernel_15404\1162770802.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_train=X_train.select_dtypes(include='object')

In [172]:
from sklearn.preprocessing import OneHotEncoder

OHE = OneHotEncoder(sparse_output = False).set_output(transform ='pandas')
cat_train_trans = OHE.fit_transform(cat_train)

In [173]:
cat_train_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,city_type_Rural,city_type_Semi-Urban,city_type_Urban
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3996,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3997,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
3998,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3999,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [174]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().set_output(transform ='pandas')

num_train_trans = scaler.fit_transform(num_train)

In [175]:
num_train_trans

,age,bmi,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,insurance_coverage_pct,previous_year_cost
0,0.774648,0.564516,0.128760,0.52,0.888889,0.071429,0.840426,0.579503
1,0.492958,0.432796,0.414148,0.10,0.888889,0.500000,0.829787,0.279852
2,0.478873,0.497312,0.468953,0.80,0.444444,0.500000,0.904255,0.740819
3,0.436620,0.481183,0.717828,0.82,0.444444,0.285714,0.680851,0.300318
4,0.309859,0.849462,0.175706,0.58,0.666667,0.214286,0.851064,0.991075
...,...,...,...,...,...,...,...,...
3995,0.591549,0.607527,0.063880,0.98,0.444444,0.214286,0.000000,0.329760
3996,0.211268,0.516129,0.788210,0.88,0.444444,0.214286,0.904255,0.978457
3997,0.647887,0.483871,0.656091,0.50,0.222222,0.500000,0.808511,0.447169
3998,0.042254,0.669355,0.133905,0.18,0.111111,0.500000,0.659574,0.018414
3999,0.788732,0.365591,0.139693,0.92,0.111111,0.428571,0.000000,0.981278

In [176]:
X_train_trans = pd.concat([cat_train_trans,num_train_trans,no_train],axis = 1)

In [177]:
X_train_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,...,stress_level,doctor_visits_per_year,insurance_coverage_pct,previous_year_cost,diabetes,hypertension,heart_disease,asthma,hospital_admissions,medication_count
0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.888889,0.071429,0.840426,0.579503,0,0,0,0,1,6
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.888889,0.500000,0.829787,0.279852,0,0,1,0,0,4
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.444444,0.500000,0.904255,0.740819,0,1,0,0,2,6
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.444444,0.285714,0.680851,0.300318,1,0,1,0,0,5
4,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.666667,0.214286,0.851064,0.991075,0,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.444444,0.214286,0.000000,0.329760,0,0,0,0,1,2
3996,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.444444,0.214286,0.904255,0.978457,0,0,0,0,1,7
3997,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.222222,0.500000,0.808511,0.447169,0,1,1,0,1,0
3998,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.111111,0.500000,0.659574,0.018414,0,0,0,0,1,2
3999,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.111111,0.428571,0.000000,0.981278,0,0,1,0,1,1

# Train model using algorithm

In [178]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()

knn.fit(X_train_trans,y_train)

KNeighborsRegressor()

## step --> 5 Feature Engineering on X_test

In [179]:
cat_test = X_test.select_dtypes(include='object')
cat_test

C:\Users\kavya\AppData\Local\Temp\ipykernel_15404\3455628393.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_test = X_test.select_dtypes(include='object')

     gender smoker physical_activity_level insurance_type   city_type
0      Male     No                     Low     Government       Urban
1      Male     No                    High        unknown  Semi-Urban
2    Female     No                  Medium        Private       Rural
3    Female     No                     Low        Private  Semi-Urban
4    Female    Yes                     Low     Government       Urban
..      ...    ...                     ...            ...         ...
995    Male    Yes                     Low     Government       Urban
996    Male     No                     Low        Private       Urban
997    Male     No                     Low     Government       Urban
998    Male    Yes                    High     Government       Urban
999    Male     No                    High        Private  Semi-Urban

[1000 rows x 5 columns]

In [180]:
cat_test_trans = OHE.transform(cat_test)
cat_test_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,city_type_Rural,city_type_Semi-Urban,city_type_Urban
0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
3,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
996,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
997,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
998,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
999,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

In [181]:
num_test = X_test[['age','bmi','daily_steps','sleep_hours','stress_level','doctor_visits_per_year','insurance_coverage_pct','previous_year_cost']]
num_test_trans = scaler.transform(num_test)
num_test_trans

,age,bmi,daily_steps,sleep_hours,stress_level,doctor_visits_per_year,insurance_coverage_pct,previous_year_cost
0,0.253521,0.591398,0.192712,0.30,0.111111,0.357143,0.691489,0.334889
1,0.295775,0.206989,0.146267,0.04,0.333333,0.285714,0.000000,0.371563
2,0.957746,0.491935,0.075384,0.56,0.000000,0.142857,0.765957,0.363767
3,0.295775,0.704301,0.552554,0.54,0.888889,0.357143,0.989362,0.334428
4,0.309859,0.655914,0.662165,0.52,0.222222,0.285714,0.542553,0.852739
...,...,...,...,...,...,...,...,...
995,0.591549,0.677419,0.168917,0.74,0.000000,0.285714,0.595745,0.688500
996,0.845070,0.567204,0.295034,0.36,0.555556,0.142857,0.978723,0.967686
997,0.112676,0.559140,0.111111,0.36,0.222222,0.357143,0.659574,0.047600
998,0.507042,0.760753,0.287746,0.76,0.222222,0.214286,0.840426,0.810936
999,0.183099,0.424731,0.230797,0.88,0.555556,0.071429,0.787234,0.627770

In [182]:
no_trans_test = X_test[['diabetes','hypertension','heart_disease','asthma','hospital_admissions','medication_count']]

In [183]:
X_test_trans = pd.concat([cat_test_trans,num_test_trans,no_trans_test],axis=1)
X_test_trans

,gender_Female,gender_Male,smoker_No,smoker_Yes,physical_activity_level_High,physical_activity_level_Low,physical_activity_level_Medium,insurance_type_Government,insurance_type_Private,insurance_type_unknown,...,stress_level,doctor_visits_per_year,insurance_coverage_pct,previous_year_cost,diabetes,hypertension,heart_disease,asthma,hospital_admissions,medication_count
0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.111111,0.357143,0.691489,0.334889,0,0,0,0,0,0
1,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.333333,0.285714,0.000000,0.371563,0,0,0,0,3,1
2,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.000000,0.142857,0.765957,0.363767,0,0,0,0,1,3
3,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.888889,0.357143,0.989362,0.334428,0,0,0,0,2,0
4,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.222222,0.285714,0.542553,0.852739,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.000000,0.285714,0.595745,0.688500,1,1,0,0,3,0
996,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.555556,0.142857,0.978723,0.967686,0,0,0,0,0,2
997,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.222222,0.357143,0.659574,0.047600,0,1,0,0,0,6
998,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.222222,0.214286,0.840426,0.810936,0,0,0,0,3,1
999,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.555556,0.071429,0.787234,0.627770,0,0,0,0,3,5

## Step 6 --> prediction on X_test

In [184]:
y_pred = knn.predict(X_test_trans)

## step 7 --> Passing y_test and y_pred to evaluation metrics

In [185]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error

In [186]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error
print('r2_score:',r2_score(y_pred,y_test))
print('MAE:',mean_absolute_error(y_pred,y_test))
print('MSE:',mean_squared_error(y_pred,y_test))
print('RMSE:',root_mean_squared_error(y_pred,y_test))

r2_score: 0.8067988162252064
MAE: 1904.1425519999998
MSE: 6836395.1653482
RMSE: 2614.650103808959

### decision tree

In [187]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()

dt.fit(X_train_trans,y_train)

DecisionTreeRegressor()

In [188]:
y_pred_dt = dt.predict(X_test_trans)

print('r2_score:',r2_score(y_pred_dt,y_test))
print('MAE:',mean_absolute_error(y_pred_dt,y_test))
print('MSE:',mean_squared_error(y_pred_dt,y_test))
print('RMSE:',root_mean_squared_error(y_pred_dt,y_test))

r2_score: 0.9484459769392792
MAE: 990.8524699999999
MSE: 2381637.3695741007
RMSE: 1543.2554453408227

### Linear Regression

In [189]:
from sklearn.linear_model import LinearRegression 

LR = LinearRegression()

LR.fit(X_train_trans,y_train)

LinearRegression()

In [190]:
y_pred_lr = LR.predict(X_test_trans)

print('r2_score:',r2_score(y_pred_lr,y_test))
print('MAE:',mean_absolute_error(y_pred_lr,y_test))
print('MSE:',mean_squared_error(y_pred_lr,y_test))
print('RMSE:',root_mean_squared_error(y_pred_lr,y_test))

r2_score: 0.9051368021875847
MAE: 1383.1247584655557
MSE: 4297762.423720489
RMSE: 2073.104537576552

### Random Forest

In [191]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor()

rf.fit(X_train_trans,y_train)

C:\Users\kavya\anaconda3\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [192]:
y_pred_rf = rf.predict(X_test_trans)

print('r2_score:',r2_score(y_pred_rf,y_test))
print('MAE:',mean_absolute_error(y_pred_rf,y_test))
print('MSE:',mean_squared_error(y_pred_rf,y_test))
print('RMSE:',root_mean_squared_error(y_pred_rf,y_test))

r2_score: 0.9772748315601256
MAE: 629.596662
MSE: 1034649.7024708686
RMSE: 1017.1773210561021

### xgboost

In [193]:
from xgboost import XGBRegressor

xgb = XGBRegressor()

xgb.fit(X_train_trans,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [194]:
y_pred_xgb = xgb.predict(X_test_trans)

print('r2_score:',r2_score(y_pred_xgb,y_test))
print('MAE:',mean_absolute_error(y_pred_xgb,y_test))
print('MSE:',mean_squared_error(y_pred_xgb,y_test))
print('RMSE:',root_mean_squared_error(y_pred_xgb,y_test))

r2_score: 0.989851176738739
MAE: 363.5780944824219
MSE: 481113.625
RMSE: 693.62353515625

## saving the model

In [200]:
import joblib

joblib.dump({'model':xgb,'cat_encoder':OHE,'num_encoder':scaler},'medical_cost.pkl')

['medical_cost.pkl']

In [201]:
medical_cost =joblib.load('medical_cost_prediction.pkl')

In [202]:
medical_cost['model']

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [203]:
medical_cost['cat_encoder']

OneHotEncoder(sparse_output=False)

In [204]:
medical_cost['num_encoder']

MinMaxScaler()